version: "3"
services:
    mysql:
        image: mysql:8.0
        # container_name: mysqlcontainer
        ports:
            - 3307:3306
        environment:
            - MYSQL_DATABASE=zengym
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./backup_data/db:/var/lib/mysql
        networks:
            - sportif_network

    frontend:
        build: ./ConceptSportifFrontEnd
        ports:
            - 4200:4200
        depends_on:
            - backend
        networks:
            - sportif_network
   
    backend:
        build: ./projet_pfe1-1
        ports:
            - 8082:8082
        depends_on:
            - mysql
        networks:
            - sportif_network
    nginx:
        image: nginx:latest
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
        ports:
            - "8888:80"
        depends_on:
            - backend
            - frontend
        networks:
            - sportif_network
   
networks:
    sportif_network:
        driver: bridge